#!/bin/sh
## Android p9070 kernel and recovery dumper
## By marduk191
## email: marduk191@gmail.com
while getopts ":br" flags;
do
    case $flags in
 b)
	## Dump boot image
	 adb shell su -c 'dd if=/dev/block/mmcblk0p8 of=/sdcard/boot.img'
	 adb pull /sdcard/boot.img
	 adb shell su -c 'rm /sdcard/boot.img'
	;;
 r)
	## Dump recovery image
	 adb shell su -c 'dd if=/dev/block/platform/msm_sdcc.1/by-num/p18 of=/sdcard/recovery.img'
	 adb pull /sdcard/recovery.img
	 adb shell su -c 'rm /sdcard/recovery.img'
	;;
 *)
	##Help
         clear
	 echo " "
	 echo "./dump -b: Dumps a copy of boot.img and ./dump -r: Dumps a copy of recovery.img " 
	 echo " "	
	;;
    esac
done
