#!/bin/bash
## Android p9070 kernel and recovery dumper
## By marduk191
## email: marduk191@gmail.com
function dumper 
{
         adb shell su -c "dd if=$1 of=$2"
	 adb pull "$2"
	 adb shell su -c "rm $2"
}
while getopts ":br" flags;
do
    case $flags in
 b)
	## Dump boot image
	 dumper /dev/block/mmcblk0p8 /sdcard/boot.img
	;;
 r)
	## Dump recovery image
	 dumper /dev/block/platform/msm_sdcc.1/by-num/p18 /sdcard/recovery.img
	;;
 *)
	##Help
         clear
	 echo " "
	 echo "./dump -b: Dumps a copy of boot.img and ./dump -r: Dumps a copy of recovery.img " 
	 echo " "	
	;;
    esac
done

