#! /bin/bash
title1="Pantech Burst boot image tools"
prompt="Functions:"
menitems=("Boot Image" "Pack Recovery" "Quit")
fucksticks=1

while [ $fucksticks -le 1 ]
do
main=$(zenity --width=300 --height=550 --list "${menitems[@]}" --column="options" --text="$prompt" --title="$title1")
case "$main" in

	"Pack Recovery")
	exec ./recovery_pack.sh | zenity --text-info

;;

	"Boot Image")
	fucksticks=2 
	
;;

	"Quit")
	fucksticks=byebye
;;

esac

done


